services:
  postgres:
    image: postgres:15-alpine
    container_name: demo-datacontract
    environment:
      POSTGRES_USER: sja-huware
      POSTGRES_PASSWORD: postgres_psw
      POSTGRES_DB: cartoons
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sja-huware -d cartoons"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: